# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiragana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=1)),
                ('english', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Katakana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=1)),
                ('english', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=10)),
                ('english', models.CharField(max_length=10)),
                ('chapter', models.IntegerField()),
            ],
        ),
    ]
