# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20170512_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiragana',
            name='english',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='hiragana',
            name='japanese',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='katakana',
            name='english',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='katakana',
            name='japanese',
            field=models.CharField(max_length=1),
        ),
    ]
