# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20170522_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=10)),
                ('english', models.CharField(max_length=10)),
                ('chapter', models.IntegerField()),
            ],
        ),
    ]
